### ISSUE TITLE
invalid syntax in NAStools/src/nastools/yamler.py

### ISSUE THREAD

**Issue by mdecker** [asobrien/NAStools#3]
Hi,
I have no idea if this is intentional but there seems to be a syntax error in line 38 of yamler.py
which (also) shows up during installation with pip.
Here is what happens on import:

```
Python 2.7.6 (default, Nov 21 2013, 15:55:38) [GCC] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import nastools.yamler
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/nastools/yamler.py", line 38
    string = ###
               ^
SyntaxError: invalid syntax
```

**Comment by asobrien** [comment]
Indeed... a syntax error (https://github.com/asobrien/NAStools/blob/master/src/nastools/yamler.py#L38) good to see someone's using the issue tracker :smile:; `yamler.py` isn't currently used in core functionality, but this should be fixed in any case.
