### ISSUE TITLE
Repository Description 'ICARTT' vs 'ICARRT'

### ISSUE THREAD

**Issue by Amsoht** [asobrien/NAStools#7]
Hey, this is a great tool! Thank you for providing. 
In the repositorie's description and in the readme file it sais 'ICARRT' instead of 'ICARTT'. Could you please change that ) especially the first one, so that the tool is easier to find for people looking for an ICARTT-reader?

Cheers

**Comment by asobrien** [comment]
Thanks for reporting this! I don't use this too much myself anymore, but I'm glad it's useful to others. I'll update the README.
